# Generated by Django 6.1 on 2026-08-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_expense_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
