# Generated by Django 6.1 on 2026-08-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_budget_is_archived_income_is_archived'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_period',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
