from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("expenses/", views.expenses, name="expenses"),
    path("expenses/export/", views.expenses_export, name="expenses_export"),
    path("income/", views.income, name="income"),
    path("income/export/", views.income_export, name="income_export"),
    path("budget/", views.budgets, name="budgets"),
    path("budget/export/", views.budgets_export, name="budgets_export"),
    path("categories/", views.categories, name="categories"),
    path("reports/", views.reports, name="reports"),
    path("expense-form/", views.expense_form, name="expense_form"),
    path("expense-form/<int:pk>/", views.expense_form, name="expense_edit"),
    path("expense-delete/<int:pk>/", views.expense_delete, name="expense_delete"),
    path("income-form/", views.income_form, name="income_form"),
    path("income-form/<int:pk>/", views.income_form, name="income_edit"),
    path("income-delete/<int:pk>/", views.income_delete, name="income_delete"),
    path("budget-form/", views.budget_form, name="budget_form"),
    path("budget-form/<int:pk>/", views.budget_form, name="budget_edit"),
    path("budget-delete/<int:pk>/", views.budget_delete, name="budget_delete"),
    path("category-form/", views.category_form, name="category_form"),
    path("category-form/<int:pk>/", views.category_form, name="category_edit"),
    path("category-delete/<int:pk>/", views.category_delete, name="category_delete"),
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("mfa/setup/", views.mfa_setup, name="mfa_setup"),
    path("mfa/login/", views.mfa_login, name="mfa_login"),
    path('ai-query/', views.ai_query, name='ai_query'),
    path('ai-result/<str:task_id>/', views.get_ai_result, name='ai_result'),
    path('forecast/', views.forecast, name='forecast'),
    path('forecast/<int:months>/', views.forecast, name='forecast_months'),
]